server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: basic
          uri: http://localhost:8082
          predicates:
            - Path=/companies/**, /products/**, 
        - id: inventory
          uri: http://localhost:8083
          predicates:
            - Path=/inventories/**, 
        - id: sales
          uri: http://localhost:8084
          predicates:
            - Path=/salesOrders/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: basic
          uri: http://basic:8080
          predicates:
            - Path=/companies/**, /products/**, 
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/inventories/**, 
        - id: sales
          uri: http://sales:8080
          predicates:
            - Path=/salesOrders/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
